###################
# BUILDER
###################

FROM node:16.17.0-alpine as builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

###################
# PRODUCTION
###################

FROM node:16.17.0-alpine as production

ENV PORT 8080

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/dist ./dist

EXPOSE 8080

CMD [ "node", "dist/main.js" ]
