FROM node:16.17.0-alpine

ENV PORT 3000

RUN apk add --no-cache python3 make g++

RUN mkdir -p /app/node_modules && chown -R node:node /app

WORKDIR /app

COPY --chown=node:node package.json yarn.lock ./

USER node

RUN yarn install --frozen-lockfile

COPY --chown=node:node . .

EXPOSE 3000

CMD ["yarn", "start:dev"]
