version: "3.3"
services:
  tiktok-ui:
    restart: always
    build:
      context: ../tiktok-ui
      dockerfile: Dockerfile.dev
    volumes:
      - ../tiktok-ui/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3001:3000
    networks:
      - tiktok

  tiktok-cms:
    restart: always
    build:
      context: ../tiktok-cms
      dockerfile: Dockerfile.dev
    volumes:
      - ../tiktok-cms/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3002:3000
    networks:
      - tiktok

  tiktok-api:
    restart: always
    build:
      context: ../tiktok-api
      dockerfile: Dockerfile.dev
    volumes:
      - ../tiktok-api/:/app
      - /app/node_modules
    ports:
      - 3003:3000
    networks:
      - tiktok

  redis:
    image: redis:7.0.4-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - tiktok

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tiktok@123
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - tiktok

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  tiktok:
    driver: bridge
