apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: pav-api

resources:
- ./resources/deployment.yaml
- ./resources/service.yaml

patches: 
- ./patches/health_check.yaml
- ./patches/update_strategy.yaml
