apiVersion: apps/v1
kind: Deployment
metadata:
  name: pav-api-deployment
spec:
  template:
    spec:
      containers:
        - name: pav-api
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
